"""Print the Postgres DDL of the API tables (``backend/sql/schema.sql`` is its output)."""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from satwiser_api import db  # noqa: E402
from sqlalchemy.dialects import postgresql  # noqa: E402
from sqlalchemy.schema import CreateIndex, CreateTable  # noqa: E402

if __name__ == "__main__":
    dialect = postgresql.dialect()
    print("-- Generated by backend/scripts/print_schema.py; the loader creates these tables.")
    for table in db.metadata.sorted_tables:
        print(str(CreateTable(table).compile(dialect=dialect)).strip() + ";\n")
        for index in table.indexes:
            print(str(CreateIndex(index).compile(dialect=dialect)).strip() + ";\n")
        print(f'ALTER TABLE "{table.name}" ENABLE ROW LEVEL SECURITY;\n')
