-- Generated by backend/scripts/print_schema.py; the loader creates these tables.
CREATE TABLE daily (
	satellite VARCHAR(8) NOT NULL, 
	date TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	a_m FLOAT, 
	f107 FLOAT, 
	ap FLOAT, 
	PRIMARY KEY (satellite, date)
);

ALTER TABLE "daily" ENABLE ROW LEVEL SECURITY;

CREATE TABLE documents (
	key VARCHAR(64) NOT NULL, 
	payload TEXT NOT NULL, 
	PRIMARY KEY (key)
);

ALTER TABLE "documents" ENABLE ROW LEVEL SECURITY;

CREATE TABLE events (
	id VARCHAR(32) NOT NULL, 
	satellite VARCHAR(8) NOT NULL, 
	kind VARCHAR(16) NOT NULL, 
	time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	orbit INTEGER NOT NULL, 
	class VARCHAR(24), 
	esa_type VARCHAR(24), 
	dv_est_mm_s FLOAT, 
	dv_esa_mm_s FLOAT, 
	esa_da_m FLOAT, 
	da_m FLOAT, 
	di_mdeg FLOAT, 
	de_1e6 FLOAT, 
	statistic FLOAT, 
	channel VARCHAR(4), 
	alarm_delay_revs FLOAT, 
	split VARCHAR(16), 
	lab_available BOOLEAN NOT NULL, 
	PRIMARY KEY (id)
);

CREATE INDEX ix_events_sat_time ON events (satellite, time);

ALTER TABLE "events" ENABLE ROW LEVEL SECURITY;

CREATE TABLE lab_windows (
	event_id VARCHAR(32) NOT NULL, 
	payload_gz BYTEA NOT NULL, 
	PRIMARY KEY (event_id)
);

ALTER TABLE "lab_windows" ENABLE ROW LEVEL SECURITY;

CREATE TABLE revolutions (
	satellite VARCHAR(8) NOT NULL, 
	orbit INTEGER NOT NULL, 
	time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	a_m FLOAT NOT NULL, 
	f107 FLOAT, 
	ap FLOAT, 
	PRIMARY KEY (satellite, orbit)
);

CREATE INDEX ix_revolutions_sat_time ON revolutions (satellite, time);

ALTER TABLE "revolutions" ENABLE ROW LEVEL SECURITY;

CREATE TABLE satellites (
	id VARCHAR(8) NOT NULL, 
	payload TEXT NOT NULL, 
	PRIMARY KEY (id)
);

ALTER TABLE "satellites" ENABLE ROW LEVEL SECURITY;

